services:
  node_exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
  fluent-bit:
    image: fluent/fluent-bit:latest
    restart: unless-stopped
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./var/log:/var/log
    environment:
      - FLUENT_ELASTICSEARCH_HOST=host.docker.internal
      - FLUENT_ELASTICSEARCH_PORT=24224

# services:
#   node_exporter:
#     image: prom/node-exporter:latest
#     restart: unless-stopped
#     # network_mode: host
#     # pid: host
#     command:
#       - '--path.procfs=/proc'
#       - '--path.sysfs=/sys'
#       - '--collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+)($$|/)'
#     volumes:
#       - /proc:/proc:ro
#       - /sys:/sys:ro
#       - /proc/sys/net/ipv4/ping_group_range:/proc/sys/net/ipv4/ping_group_range:rw  # 追加
#     ports:
#      - '9100:9100'
#     cap_add:
#       - SYS_ADMIN
#       - NET_ADMIN  # 追加
#     security_opt:
#       - seccomp:unconfined  # 追加