apiVersion: 1

datasources:
  - name: Uptrace Tempo Project 1
    type: tempo
    access: proxy
    url: http://host.docker.internal:14318/api/tempo/1
    editable: true
    jsonData:
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'secret_token'

  - name: Uptrace Prometheus Project 1
    type: prometheus
    access: proxy
    url: http://host.docker.internal:14318/api/prometheus/1
    editable: true
    jsonData:
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'secret_token'

  - name: Uptrace Prometheus Project 2
    type: prometheus
    access: proxy
    url: http://host.docker.internal:14318/api/prometheus/2
    editable: true
    jsonData:
      httpHeaderName1: 'Authorization'
    secureJsonData:
      httpHeaderValue1: 'secret_token'

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
