services:
  app:
    user: root
    image: mcr.microsoft.com/devcontainers/java:21-bullseye
    volumes:
      - ./example-app:/workspace
      - ./example-app/.devcontainer/m2_repo:/root/.m2
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
    command: /bin/sh -c 'while sleep 1000; do :; done'
  database:
    image: postgres:14.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
  monitoring:
    image: debian 
  load-tester:
    image: grafana/k6
    volumes:
      - ./load-tester:/workspace