server:
  port: 8080
  host: 0.0.0.0
  executor-service:
    core-pool-size: 50000
    max-pool-size: 50000
javax:
  sql:
    DataSource:
      PaymentDS:
        dataSourceClassName: com.zaxxer.hikari.HikariDataSource
        # dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        dataSource:
          jdbcUrl: jdbc:postgresql://database:5432/postgres
          username: postgres
          password: password
          maximumPoolSize: 1000
